# Instantaneously award the player the xp instead of creating an xp orb
instant-xp: false

# Choose between different functions for calculating the earned xp
# 'SKELUN' give the player 12 points for levels 0-9, 15 for 10-19, 21 for 20-29 and 33 for 30+ (xp-arg does nothing)
# 'CONSTANT' gives the player the amount of points denoted by xp-arg
# 'PROPORTIONAL' gives the player the percentage denoted by xp-arg of the amount needed to complete that level
# 'LEVELED' gives the player their level multiplied by xp-arg
xp-function: 'SKELUN'
xp-arg: 15

# Setting any delta to 0 or below will disable it
cutting-delta: 15
digging-delta: 64
farming-delta: 24
mining-delta: 34
traveling-delta: 85